name: Docker publish apm to docker.io

on:
  workflow_dispatch:
  push:
    branches:
      - 'apm'

permissions:
  contents: read

concurrency:
  group: apm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.repository == 'mbtools/verdaccio'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Package Verdaccio Pro Plugins
        run: |
          cd abappm/plugins/@verdaccio-pro/database
          npm pack
          cd /

      - name: Copy Dockerfile for Root Build Context
        run: |
          cp abappm/docker/.dockerignore ./.dockerignore
          cp abappm/docker/Dockerfile ./Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          driver-opts: network=host

      - name: Login Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Docker Image Tags
        id: docker_meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: abappm/registry
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'apm') }}
            type=sha

      - name: Set build date
        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Set Verdaccio version
        run: echo "VERDACCIO_VERSION=$(node -p 'require(\"./packages/verdaccio/package.json\").version')" >> $GITHUB_ENV

      - name: Docker Build & Push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            BUILD_SHA=${{ github.sha }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            VERDACCIO_VERSION=${{ env.VERDACCIO_VERSION }}
