name: CI Windows

on:
  workflow_dispatch:
  push:
  pull_request:
    paths:
      - .changeset/**
      - .github/workflows/ci-win.yml
      - 'packages/**'
      - 'test/**'
      - 'docker-examples/**'
      - 'jest/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
permissions:
  contents: read
concurrency:
  group: ci-win-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: setup verdaccio
    services:
      verdaccio:
        image: verdaccio/verdaccio:nightly-master
        ports:
          - 4873:4873
        env:
          NODE_ENV: production
          options: >-
            --health-cmd="curl -f http://0.0.0.0:4873/-/ping || exit 1"
            --health-interval=10s   
            --health-timeout=20s    
            --health-retries=6
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install dependencies with a custom registry
        uses: ./.github/actions/install-app-win
  test:
    needs: [prepare]
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        # node_version: [18, 20, 21, 22, 23]
        node_version: [22]
    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build application with Node ${{ matrix.node_version }}
        uses: ./.github/actions/build-app-win
        with:
          node-version: ${{ matrix.node_version }}
      - name: Test
        run: pnpm test
